'use strict';
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {chromium}=require('playwright');
const fs=require('node:fs/promises');
let server,browser;
(async()=>{
  server=spawn('python3',['-m','http.server','0','--bind','127.0.0.1'],{cwd:require('node:path').join(__dirname,'..'),env:{...process.env,PYTHONUNBUFFERED:'1'}});
  const port=await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{const m=String(d).match(/port (\d+)/);if(m)resolve(m[1]);});server.on('error',reject);});
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});
  const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});
  const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));const page=await context.newPage();
  const base=`http://127.0.0.1:${port}`;
  await page.goto(base+'/graph.html');await page.waitForSelector('.analysis-chip');
  assert.equal(await page.locator('.expression-row').count(),2);
  assert.match(await page.locator('#analysisResults').innerText(),/交點/);
  await page.locator('#exampleSelect').selectOption('quadratic');await page.locator('#param-a').fill('2');
  await page.waitForTimeout(450);assert.equal(await page.locator('#parameterPanel').isVisible(),true);
  const input=page.getByRole('textbox',{name:'算式 1',exact:true});await input.fill('y=1/x');await page.waitForTimeout(450);
  assert.equal(await input.getAttribute('aria-invalid'),'false');
  await input.fill('alert(1)');await page.waitForTimeout(300);assert.equal(await input.getAttribute('aria-invalid'),'true');
  await input.fill('y=x^2-2');await page.waitForTimeout(400);
  for(const example of ['circle','trig','rational','parametric','polar','points']){
    await page.locator('#exampleSelect').selectOption(example);await page.waitForTimeout(400);
    assert.equal(await page.locator('.expression-input[aria-invalid=true]').count(),0,example);
    const colored=await page.locator('#graphCanvas').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=4)if(Math.max(d[i],d[i+1],d[i+2])-Math.min(d[i],d[i+1],d[i+2])>80)n++;return n;});
    assert.ok(colored>100,`${example}: rendered colored curves`);
  }
  await page.locator('#exampleSelect').selectOption('parametric');await page.locator('#tMax').fill('-1');await page.locator('#tMax').press('Tab');
  assert.equal(await page.locator('#tMax').inputValue(),'2π','invalid t range restores the preserved symbolic source');
  const restoredT=await page.locator('#tMax').evaluate(input=>window.MathExact.scalar(input.value).value);
  assert.ok(Math.abs(restoredT-2*Math.PI)<1e-12,'restored symbolic range evaluates to 2π');
  await page.locator('#exampleSelect').selectOption('quadratic');await page.locator('#param-a').fill('2.5');await page.locator('#param-a').press('Tab');
  await page.locator('#shareGraph').click();const share=await page.locator('#graphShareURL').inputValue();assert.match(share,/#g=/);
  await page.getByRole('button',{name:'關閉',exact:true}).click();
  const shared=await context.newPage();await shared.goto(share);assert.equal(await shared.locator('#param-a').inputValue(),'2.5');await shared.close();
  await page.waitForTimeout(400);await page.reload();assert.equal(await page.locator('#param-a').inputValue(),'2.5');
  const before=await page.locator('#viewReadout').innerText();await page.locator('#zoomIn').click();await page.waitForTimeout(200);assert.notEqual(await page.locator('#viewReadout').innerText(),before);
  await page.locator('#graphCanvas').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('0');
  await page.locator('#showTangent').check();await page.locator('#probeX').fill('2');await page.waitForTimeout(200);assert.match(await page.locator('#probeResult').innerText(),/斜率/);
  await page.locator('#fitView').click();
  const downloadEvent=page.waitForEvent('download');await page.locator('#exportGraph').click();const download=await downloadEvent;const bytes=await fs.readFile(await download.path());assert.equal(bytes.subarray(1,4).toString(),'PNG');assert.ok(bytes.length>1000);
  await page.locator('#homeView').click();await page.waitForTimeout(300);await page.screenshot({path:'/tmp/math-graph-desktop.png',fullPage:true});
  const mobile=await context.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.goto(base+'/graph.html');await mobile.waitForTimeout(400);
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no mobile horizontal overflow');
  await mobile.locator('#exampleSelect').selectOption('circle');await mobile.waitForTimeout(450);await mobile.locator('#graphCanvas').scrollIntoViewIfNeeded();await mobile.screenshot({path:'/tmp/math-graph-mobile.png',fullPage:true});
  const rect=await mobile.locator('#graphCanvas').boundingBox();
  const cdp=await context.newCDPSession(mobile),cx=rect.x+rect.width/2,cy=rect.y+rect.height/2;
  const touch=(x,y,id)=>({x,y,id,radiusX:3,radiusY:3});
  const touchBefore=await mobile.locator('#viewReadout').innerText();
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(cx-30,cy,1),touch(cx+30,cy,2)]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(cx-65,cy,1),touch(cx+65,cy,2)]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.waitForTimeout(300);
  assert.notEqual(await mobile.locator('#viewReadout').innerText(),touchBefore,'pinch zoom changes view');
  await mobile.setViewportSize({width:820,height:1180});await mobile.waitForTimeout(250);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no tablet overflow');
  await mobile.goto(base+'/graph.html#g=invalid');await mobile.waitForTimeout(250);assert.equal(await mobile.locator('.expression-row').count(),2);
  await page.goto(base+'/index.html');await page.locator('.graph-entry').click();assert.ok(page.url().endsWith('/graph.html'));
  assert.deepEqual(errors,[]);console.log('PASS graph browser checks: all graph types, invalid input, sliders, sharing, persistence, zoom, keyboard, tangent, fit, PNG, mobile, homepage entry');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.kill();});
